window.TOOTOO_CONFIG = {
  owner: 'theo-armour',
  repo: '2025',
  appName: '2025',
  storagePrefix: 'ta-2025',
  sourceRepoUrl: 'https://github.com/theo-armour/2025',
  themeColor: '#2e86c1',
  subtitle: '',
  faviconLetters: '25',
  faviconColor: '#2e86c1',
  faviconFile: 'favicon.ico',
  subtitle: 'a GitHub repository browser',
  headingFontUrl: 'https://fonts.googleapis.com/css2?family=Patua+One&display=swap',
  headingFont: '"Patua One", serif',
  hiddenFiles: [ 'tootoo.config.js' ],
  hiddenFolders: [ 'Images' ],
};
